Add net price and list price as default fields
richardhaeser-com/sw-tweakwise pull request #20
Opened 2023-06-21 08:33 UTC by ruudwelten

As the net price and list price are usually used in the display of search results and product listings I think these should be included in the feed by default.

In the available data in the template there was no net price field available which is why I calculated it from the taxes.

2023-06-21 19:08 UTC, haassie requested changes

2023-06-21 19:08 UTC, haassie commented on src/Resources/views/tweakwise/product.xml.twig
> +            <netprice>{{ priceNet|round(2, 'common') }}</netprice>
We can not add properties on this level in the feed. If we have custom prices, we should have them in the attributes. There you can also find the listprice already.

2023-06-26 06:27 UTC, ruudwelten commented on src/Resources/views/tweakwise/product.xml.twig
> +            <netprice>{{ priceNet|round(2, 'common') }}</netprice>
@haassie Excuse me, I must have missed the list price already in there. How about the implementation for the net price? I've updated the PR by adding it in the attributes section.

2023-06-30 12:36 UTC, haassie approved these changes

2023-06-30 12:36 UTC, merged